version: '3.8'

services:
  # O Site e Servidor (Aplicação)
  app:
    build: .
    container_name: siscqt-app
    ports:
      - "3000:3000" # Porta do Site
      - "8080:8080" # Porta da API
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/siscqt_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=siscqt_db
      # A sua chave da API da Gemini deve ser colocada num ficheiro .env
      # Exemplo de .env:
      # GEMINI_API_KEY=AIzaSy...
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENABLE_MOCK_AUTH=true
      - MSAL_JWKS_URI=https://login.microsoftonline.com/c580bd4a-fb89-4bde-b6ae-715befa1ab31/discovery/v2.0/keys
      - MSAL_AUDIENCE=df5b2c78-c26b-47ae-aa8c-86dab74752fb
      - MSAL_ISSUER=https://login.microsoftonline.com/c580bd4a-fb89-4bde-b6ae-715befa1ab31/v2.0
    volumes:
      - .:/app # Sincroniza a tua pasta local com o Docker (Hot Reload)
      - /app/node_modules # Evita apagar os módulos dentro do Docker
    depends_on:
      - db
    restart: always

  # A Base de Dados
  db:
    image: postgis/postgis:15-3.3
    container_name: siscqt-postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: siscqt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: